name: Google books API tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
      - uses: actions/checkout@v2

      - name: install newman and htmlextra dependencies 
        run: npm install -g newman -g newman-reporter-htmlextra

      - name: Run the tests
        run: newman run collection.json -r cli,htmlextra,junit

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: tests-results
          path: newman/*.xml
      - uses: actions/upload-artifact@v3
        with:
          name: test-rappotr
          path: newman/*.html
